package:
  name: example_conda_app
  version: {{ environ.get('GIT_DESCRIBE_TAG', '')[1:]+environ.get('GIT_DESCRIBE_NUMBER', '') }}

source:
  path: ../

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - pandas

test:
  requires:
    - pytest
  imports:
    - example_conda_app
  commands:
    - py.test ../example_conda_app/test/test_app.py
